name: Build and deploy to didapp/dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18.3]

    steps:
    - uses: actions/checkout@master

    - name: Select node version 12.8.3
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm packages
      run: |
        npm install --no-progress --loglevel silent --no-shrinkwrap --no-fund

    - name: npm build and package
      run: |
        npm run package:client
        npm run build:server
      env:
        DEBUG: webpack*
        NODE_ENV: production

    - name: 'Deploy to didapp/dev'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'didapp'
        slot-name: 'dev'
        publish-profile: ${{ secrets.DIDAPP_DEV_PUBLISH_PROFILE }}
        package: .