name: Build and deploy to didapp/dev

on:
  push:
    branches:
      - feature/dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.3'

    - name: npm install, build and package
      run: |
        npm install
        npm run package:client
        npm run build:server

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'didapp'
        slot-name: 'dev'
        publish-profile: ${{ secrets.DIDAPP_DEV_PUBLISH_PROFILE }}
        package: .